// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: paillier.proto

package paillierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 公開鍵
type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             []byte                 `protobuf:"bytes,1,opt,name=n,proto3" json:"n,omitempty"`
	NSquare       []byte                 `protobuf:"bytes,2,opt,name=n_square,json=nSquare,proto3" json:"n_square,omitempty"`
	G             []byte                 `protobuf:"bytes,3,opt,name=g,proto3" json:"g,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_paillier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_paillier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_paillier_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetN() []byte {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *PublicKey) GetNSquare() []byte {
	if x != nil {
		return x.NSquare
	}
	return nil
}

func (x *PublicKey) GetG() []byte {
	if x != nil {
		return x.G
	}
	return nil
}

// 秘密鍵
type PrivateKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     *PublicKey             `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Lambda        []byte                 `protobuf:"bytes,2,opt,name=lambda,proto3" json:"lambda,omitempty"`
	Mu            []byte                 `protobuf:"bytes,3,opt,name=mu,proto3" json:"mu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKey) Reset() {
	*x = PrivateKey{}
	mi := &file_paillier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKey) ProtoMessage() {}

func (x *PrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_paillier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKey.ProtoReflect.Descriptor instead.
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return file_paillier_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateKey) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PrivateKey) GetLambda() []byte {
	if x != nil {
		return x.Lambda
	}
	return nil
}

func (x *PrivateKey) GetMu() []byte {
	if x != nil {
		return x.Mu
	}
	return nil
}

// 暗号文
type Ciphertext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             []byte                 `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ciphertext) Reset() {
	*x = Ciphertext{}
	mi := &file_paillier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ciphertext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ciphertext) ProtoMessage() {}

func (x *Ciphertext) ProtoReflect() protoreflect.Message {
	mi := &file_paillier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ciphertext.ProtoReflect.Descriptor instead.
func (*Ciphertext) Descriptor() ([]byte, []int) {
	return file_paillier_proto_rawDescGZIP(), []int{2}
}

func (x *Ciphertext) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

var File_paillier_proto protoreflect.FileDescriptor

const file_paillier_proto_rawDesc = "" +
	"\n" +
	"\x0epaillier.proto\x12\bpaillier\"B\n" +
	"\tPublicKey\x12\f\n" +
	"\x01n\x18\x01 \x01(\fR\x01n\x12\x19\n" +
	"\bn_square\x18\x02 \x01(\fR\anSquare\x12\f\n" +
	"\x01g\x18\x03 \x01(\fR\x01g\"h\n" +
	"\n" +
	"PrivateKey\x122\n" +
	"\n" +
	"public_key\x18\x01 \x01(\v2\x13.paillier.PublicKeyR\tpublicKey\x12\x16\n" +
	"\x06lambda\x18\x02 \x01(\fR\x06lambda\x12\x0e\n" +
	"\x02mu\x18\x03 \x01(\fR\x02mu\"\x1a\n" +
	"\n" +
	"Ciphertext\x12\f\n" +
	"\x01c\x18\x01 \x01(\fR\x01cB\rZ\v/paillierpbb\x06proto3"

var (
	file_paillier_proto_rawDescOnce sync.Once
	file_paillier_proto_rawDescData []byte
)

func file_paillier_proto_rawDescGZIP() []byte {
	file_paillier_proto_rawDescOnce.Do(func() {
		file_paillier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paillier_proto_rawDesc), len(file_paillier_proto_rawDesc)))
	})
	return file_paillier_proto_rawDescData
}

var file_paillier_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_paillier_proto_goTypes = []any{
	(*PublicKey)(nil),  // 0: paillier.PublicKey
	(*PrivateKey)(nil), // 1: paillier.PrivateKey
	(*Ciphertext)(nil), // 2: paillier.Ciphertext
}
var file_paillier_proto_depIdxs = []int32{
	0, // 0: paillier.PrivateKey.public_key:type_name -> paillier.PublicKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_paillier_proto_init() }
func file_paillier_proto_init() {
	if File_paillier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paillier_proto_rawDesc), len(file_paillier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paillier_proto_goTypes,
		DependencyIndexes: file_paillier_proto_depIdxs,
		MessageInfos:      file_paillier_proto_msgTypes,
	}.Build()
	File_paillier_proto = out.File
	file_paillier_proto_goTypes = nil
	file_paillier_proto_depIdxs = nil
}
